// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /books/{bookId}"
  | "GET /books"
  | "GET /books/{bookId}"
  | "GET /loans/overdue"
  | "GET /me/loans"
  | "POST /books"
  | "POST /me/loans"
  | "POST /me/loans/{loanId}/return"
  | "PUT /books/{bookId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /books/{bookId}": { kind: "scope", scope: "books:manage" },
  "GET /books": { kind: "signedIn" },
  "GET /books/{bookId}": { kind: "signedIn" },
  "GET /loans/overdue": { kind: "scope", scope: "loans:read-overdue" },
  "GET /me/loans": { kind: "scope", scope: "loans:read" },
  "POST /books": { kind: "scope", scope: "books:manage" },
  "POST /me/loans": { kind: "scope", scope: "loans:borrow" },
  "POST /me/loans/{loanId}/return": { kind: "scope", scope: "loans:return" },
  "PUT /books/{bookId}": { kind: "scope", scope: "books:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
