// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "books:manage"
  | "loans:borrow"
  | "loans:read"
  | "loans:read-overdue"
  | "loans:return";

export type Role =
  | "Librarian"
  | "Member";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["books:manage", "loans:borrow", "loans:read", "loans:read-overdue", "loans:return"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Librarian", "Member"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Librarian": ["books:manage", "loans:read-overdue"],
  "Member": ["loans:borrow", "loans:read", "loans:return"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Librarian": ["Librarians"],
  "Member": ["Members"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Librarian": [],
  "Member": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
